### ISSUE TITLE
Allow total exclusion of archived items

### ISSUE THREAD

**Issue by jchrom** [llad/export-for-trello#19]
I know this has been dealt with by putting the cards on two separate worksheets. However, as the number of archived items on a given board increases over time, the amount of exported data grows rapidly, which is not very efficient. Especially if you need to export cards periodically (this is what we need to do at our organization). Each time we export 'current' cards, an avalanche of archived items gets exported as well (albeit on a different worksheet), and their numbers are growing each time. This worksheet is of no value to me and I delete it right away.

How complicated would it be to include an option, say in Google Chrome Extension settings, so that I can set it only to export not-archived cards?

**Comment by llad** [comment]
I hear you. I mostly regret adding the archived card functionality. I'm not interested in adding complexity to the extension so not planning on adding options. When I get the time, I'd like to make a more advanced solution that isn't built as a Chrome extension.

I'm not sure where the performance hit comes from when processing a board with lots of archived cards. It uses the standard Trello JSON export which always includes archived items, so if that request takes the bulk of the time, then this proposed option wouldn't make it much more efficient. You'd have to re-write the extension from scratch to leverage the Trello API.

If the performance hit comes mostly from writing to the Excel file, then you can just comment out lines 136 and 137 in trelloexport.js and it won't write any of the archived cards.

If the performance hit comes from processing the data (unlikely), then you have a bit more work of filtering out archived (closed) cards/lists at the beginning of the $.each iterations for lists and cards.

**Comment by jchrom** [comment]
Thanks for the response! I' gonna have a look at the js file.
