### ISSUE TITLE
Seems disabled

### ISSUE THREAD

**Issue by desmond-dsouza** [llad/export-for-trello#29]
I installed this, but cannot get to its options to configure it, and it seems disabled (see small screenshots). Tried uninstalling & reinstalling as well. Any suggestions?

Chrome Version 51.0.2704.106 (64-bit), on OSX 10.9.5

It had worked for me some months ago.

Thanks!

![image](https://cloud.githubusercontent.com/assets/4407158/16511084/ff533184-3f11-11e6-9d07-d8d439dc81ba.png)

![image](https://cloud.githubusercontent.com/assets/4407158/16511096/30134f34-3f12-11e6-9139-f78b69259ad9.png)

**Comment by fabiosilva42** [comment]
Same here, anyone?

**Comment by llad** [comment]
The extension has no features accessible through the Chrome toolbar. So it will look disabled here. Follow the instructions for usage from the extension's page on the [Web Store](https://chrome.google.com/webstore/detail/export-for-trello/nhdelomnagopgaealggpgojkhcafhnin).
